config/routes.rb
Ideaspan::Application.routes.draw do
  root :to => 'cards#index'
  
  resources :cards
  match '/auth/:provider/callback', :to => 'sessions#create'

  
  resources :users do
    member do
      get 'show'
    end
  end

end

app/models/authorization.rb
class Authorization < ActiveRecord::Base
  belongs_to :user
  
  def self.find_from_hash(hash)
    find_by_provider_and_uid(hash[:provider], hash[:uid])
  end
  
  def self.create_from_hash(hash, user)
    @auth = self.new(:user_id => user.id, :provider => hash[:provider], :uid => hash[:uid], :token => hash[:credentials][:token])
    if @auth.save
      @auth
    else
      return false
    end
  end

end

app/models/card.rb
class Card < ActiveRecord::Base
  scope :root_cards, where(:parent_id => nil)
	belongs_to :parent, :class_name => "Card", :foreign_key => "parent_id"
	belongs_to :grandparent, :class_name => "Card", :foreign_key => "grandparent_id"
	has_many :children, :class_name => "Card", :foreign_key => "parent_id", :dependent => :destroy
	has_many :grandchildren, :class_name => "Card", :foreign_key => "grandparent_id"
	
  belongs_to :user
  validates :name, :presence => true


   
  def has_children?
    return !self.children.nil?
  end

   
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :authorizations
  has_many :cards
  
  after_create do |user|
      a = Card.new
        a.name = user.name
        a.description = "Edit this card to add a bio!"
        a.parent = Card.where(:name => "People")[0]
        a.user_id = user.id
      a.save
  end
  
  
  def self.new_from_hash(hash)
    user = User.new(:name => hash[:info][:name], :email => hash[:info][:email])
    if user.save
      return user
    else
      retun false
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  
  def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def signed_in?
      !!current_user
    end

    def current_user=(user)
      @current_user = user
      session[:user_id] = user.id
    end
    
    
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.root_cards
    @user = current_user
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cards }
    end
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
    @card = Card.find(params[:id])
    @cards = @card.children
    if (params[:level])
      if (params[:level] == '1')
        @cards = @card.parent.children
        @card = @card.parent
      elsif (params[:level] == '2')
        if @card.parent.parent.nil?
          @cards = [@card.parent]
        else
          @cards = @card.parent.parent.children
          @card = @card.parent.parent
        end
      end
    end

    
    @user = current_user
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @card }
    end
  end

  # GET /cards/new
  # GET /cards/new.json
  def new
    @card = Card.new(:parent_id => params[:parent_id])

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @card }
      format.js
    end
  end

  # GET /cards/1/edit
  def edit
    @card = Card.find(params[:id])
    
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(params[:card])
    @card.user = current_user
    
    if @card.parent_id != nil
      @card.grandparent_id = @card.parent.parent_id
    else
      @card.grandparent_id = nil
    end
    
    respond_to do |format|
      if @card.save
        format.html { redirect_to cards_path, notice: 'Card was successfully created.' }
        format.json { render json: @card, status: :created, location: @card }
      else
        format.html { render action: "new" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
      format.js
    end
  end

  # PUT /cards/1
  # PUT /cards/1.json
  def update
    @card = Card.find(params[:id])

    respond_to do |format|
      if @card.update_attributes(params[:card])
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { head :ok }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @card.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    respond_to do |format|
      format.html { redirect_to cards_url }
      format.json { head :ok }
      format.js
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create

    omnihash = request.env['omniauth.auth']
    unless @auth = Authorization.find_from_hash(omnihash)
      #store token if its new
      #create new user
      new_user = User.new_from_hash(omnihash)
       @auth = Authorization.create_from_hash(omnihash, new_user)
     end
     # Log the authorizing user in.
     session[:user_id] = @auth.user.id
     redirect_to user_path(@auth.user)
  end
  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @card = @user.cards.first
    redirect_to card_path(@card)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
      @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end

    def signed_in?
      !!current_user
    end
    
    def current_user=(user)
      @current_user = user
      session[:user_id] = user.id
    end
    
end

app/helpers/cards_helper.rb
module CardsHelper
  
  def div_for_level(level)
    "span#{16-level.to_i*3} card-children"
  end

  def left_arrow(card)
    a = ""
    if !card.parent.nil?   
      a = link_to(image_tag("/left-arrow.png", :width => '22px' ), card_path(card.parent.parent))
    end
      "<div class='span1 arrow leftpoint'> #{a} </div>"
  end
  
  def right_arrow(card)
    a = ""
    if !card.children.empty?   
      a = link_to(image_tag("/right-arrow.png", :width => '22px' ), card_path(card.parent.parent.parent.parent.parent))
    end
      "<div class='span1 arrow rightpoint'> #{a} </div>"
  end
    
  def render_card_tree(root_card, level)
    if level < 5
      content_tag_for(:div, root_card, :class => "row #{ !root_card.parent.nil?}") do
        
          render_string = ""
          
          if (level == 0) then render_string << left_arrow(root_card) end
          
          render_string << render(:partial => '/cards/card', :locals => {:card => root_card})
          render_string << "<div class='#{div_for_level(level+1)} '>"
          
            root_card.children.each do |c|
              render_string << render_card_tree(c, level+1)
            end
            
          render_string << "</div>"
          
            
          render_string.html_safe
      end
    else
     right_arrow(root_card) 
    end  
  end
  
  def render_new_card(card)
    content_tag_for(:div, card, :class => "row ") do
      render_string = ""
      render_string << render(:partial => '/cards/card', :locals => {:card => card})
      render_string << "<div class='card-children' ></div>"
      render_string.html_safe
    end
  end

  def grandparent_ID(card)
    grandparent = has_parent(card, 4)
    if (grandparent == false)
      return 1
    else
      return grandparent.id
    end
  end
  
  def great_grandparent(card)
    return has_parent(card, 5)
  end
  
  def has_parent(card,level)
    if level == 0
      return card
    elsif !card.parent.nil?
      level = level - 1
      return has_parent(card.parent,level)
    else
      return false
    end
  end
  
  def parent_card_list(card)
    list = [card]
    #unshifts add to beginning of list
    list.unshift list.first.parent until list.first.parent.nil?
    list.unshift  until list.first.parent.nil? 
    list.map{|c| link_to(c.name, c)}.join(" / ").html_safe
  end
  

end

app/helpers/users_helper.rb
module UsersHelper
  
  def card_pic(user)
    uid = user.authorizations.first.uid
    return "https://graph.facebook.com/#{uid}/picture"
  end
  
  def home_card(user)
    if user.cards.first.parent.name == "People"
      return user.cards.first
    else
      return user.cards.first
    end
  end
  
end

app/views/cards/_card.html.erb
<div class="span3 single">
	<div class="card-outline">
		<div class="header" style="float:left">
	
			<% if !card.user.nil? and (card.user != current_user) %>
				<div class="title" style="width:165px; float:left" >
					<%= card.name %>
				</div>

				<div style="float:left; margin-left:5px">
					<%= link_to image_tag(card_pic(card.user), :width => "20px"), card_path( home_card(card.user) )%>
				</div>
			<% else %>
			<div class="title" >
				<%= card.name %>
			</div>
			<% end %>

			
		</div>
		<div class="links">
			<% if signed_in? %>
			<%= link_to 'O', card, :class => "open" %>
			<%= link_to 'E', edit_card_path(card), :remote => true, :class => "edit" %>
			<%= link_to 'D', card, confirm: "Are you sure you want to delete card #{card.name}?", method: :delete, :remote => true, :class => "delete" %>
			<%= link_to 'N', new_card_path( :parent_id => card.id ), :remote => true, :class => "new" %>
			<% end %>
		</div>
		<% if !card.description.empty? %>
				<div class="description">
					<%= card.description %>
				</div>	
				<% end %>
		<div class="grab-here"></div>
	</div>
</div>

app/views/cards/_form.html.erb
<div class="card frame row", id="<%= dom_id(@card) %>">

	<div class="span3 single">
	<%= form_for @card, remote: true do |f| %>
	  <% if @card.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

	      <ul>
	      <% @card.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>

	  <div class="title">
	    <%= f.text_field :name %>
	  </div>
	  <div class="description">
	    <%= f.text_area :description, :style =>"height:50px" %>
	  </div>
	  <div class="field">
	    <%= f.hidden_field :parent_id %>
	  </div>
	  <div class="actions">
	    <%= f.submit %>
	  </div>
	</div>

<% end %>

app/views/cards/_newcard.html.erb
<%= content_tag_for(:div, root_card, :class => "row ") do %>

<%= render 'card' %>

<% end %>

app/views/cards/create.js.erb
<% if @card.new_record? %>

$('form').fadeOut();
$('form').remove();

<% else %>

var spanClass = $("#new_card").findSpan();
$("#new_card").replaceWith("<%=  j render_new_card(@card) %>");
$("#<%= dom_id(@card) %> .card-children").addClass(spanClass);
$('.links').hide();

<% end %>

$('container').selectState();

app/views/cards/destroy.js.erb
$().left();
$('#<%= dom_id(@card) %>').fadeOut( 500, function(){
$('#<%= dom_id(@card) %>').remove();
});

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/edit.js.erb
$('container').editingState();

a = $("#<%= dom_id(@card) %> .span3 ")[0]
$(a).html("<%= j render 'form'  %>");
$(".edit_card").initializeForm();

app/views/cards/index.html.erb
<div class="container">

	<div class="row breadcrumb page-head" style="margin-left: 10px">
		    <div class=" span12 parent-list">	
			<div class="parent-list-inner">
			  Home
			</div>
		    </div>
		
		
		    <div class="span3">
			
			<% if !signed_in? %>
		        <%= link_to( image_tag("/facebook-login.png"), '/auth/facebook')%>
		        <% else %>
			<button class="btn primary small new ">New</button>
			<button class="btn primary small edit">Edit</button>
			<button class="btn danger small delete">Delete</button>
			<button class="btn primary small submit">Submit</button>
			<% end %>
			
		    </div>
		    <div class="span1">
			<div class="spinner">
			</div>
		    </div>
		
	</div>
	
	
	<div class="Whiteboard">
		<% @cards.each do |card| %>
			<%= render_card_tree(card, 0) %>
		<% end %>	
	</div>

	
</div>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/new.js.erb
$().editingState();

var grandparent_ID;

if ($("#<%= dom_id(@card.parent) %>").atEnd()) {
  grandparent_ID = "<%= grandparent_ID(@card) %>";
  $("#<%= dom_id(@card.parent) %>").shift("left", function(){
    $('.highlight.active .new').click(); //reclick the new button
  });
} else {
  $("#<%= dom_id(@card.parent) %> .card-children:first").append("<%= j render 'form'  %>");
  $("#new_card").initializeForm();
}

app/views/cards/show.html.erb
<div class="container-fluid">
	<div class="row breadcrumb page-head" style="margin-left: 10px">
		    <div class=" span12 parent-list">	
			<div class="parent-list-inner">
			<%= parent_card_list(@card)%>
			
			</div>
		    </div>
		
		    <div class="span1">
			<div style="height:1px"></div>
			<div class="spinner">
			</div>
		    </div>
			
		    <div class="span3">
				<% if !signed_in? %>
			        <%= link_to( image_tag("/facebook-login.png"), '/auth/facebook')%>
			        <% else %>
				<button class="btn primary small new ">New</button>
				<button class="btn primary small edit">Edit</button>
				<button class="btn danger small delete">Delete</button>
				<button class="btn primary small submit">Submit</button>
				<%= link_to image_tag(card_pic(current_user), :class => "picture"), card_path( home_card(current_user) )%>
				
				<% end %>	
		    </div>
	</div>

	<% if !@card.nil? %>	
		<div class="Whiteboard">
			<% @cards.each do |card| %>
				<%= render_card_tree(card, 0) %>
			<% end %>
	<% end %>
</div>

app/views/cards/update.js.erb
a = $("#<%= dom_id(@card) %> .single")[0];

$(a).replaceWith("<%=  j render(@card) %>");

$("#<%= dom_id(@card) %> .header:first").click();
$('.links').hide();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideaspan</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/show.html.erb
<%= @user.name %>